# This is a basic workflow to help you get started with Actions

name: Docker Publish

# Controls when the workflow will run
on:
  schedule:
    - cron: '37 6 * * *'
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: rcampusa/docker-analysis

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Download License
        uses: wei/wget@v1
        with:
          args: -O stata.lic ${{ secrets.STATA_LICENSE }}

      - name: Download Stata
        uses: wei/wget@v1
        with:
          args: -O stata_install.tar.gz ${{ secrets.STATA_URL }}

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: rcampusa/docker-analysis:latest
